### ISSUE TITLE
--debug should give a traceback

### ISSUE THREAD

**Issue by okdistribute** [joehand/dat-next#102]
if I do --debug, when it encounters an error and forwards it`ui.exitErr(err)`, it should do a `console.trace(err)`

**Comment by joehand** [comment]
FYI: right now the `--debug` option [does not work](https://github.com/joehand/dat-next/blob/master/bin/cli.js#L18). Had a heck of a time trying to get `--debug` and `DEBUG=dat` to both work.

But yes, good idea and we can do it for if `process.env.DEBUG` has `dat`.
