### ISSUE TITLE
export dat-node as module

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#112]
We could export dat-node as module so people could `npm install dat` then use `var dat = require('dat')`. (idea from @yoshuawuyts, opening issue so I don't forget). 

Benefits:

* Less things to remember
* Easier to require!

Downsides:

* Could be confusing in documentation 
* Extra module downloads for people using dat-node (e.g. the prompt module, which is only used in CLI)

**Comment by okdistribute** [comment]
i think it'll be easier in documentation! +1

**Comment by joehand** [comment]
This issue was moved to datproject/dat#616
