### ISSUE TITLE
make --no-import the default

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#15]
create and sync have a --no-import option. Might make sense to make that the default and have an `-i` or `--import` options.

```
<pfrazee> jhand: I think it'd be better to make --no-import the default
<pfrazee> jhand: if dat were an unversioned network host (aka a static web server)
 then reflecting the current state would be no problem, by default. 
But since it's writing to an immutable log, I want to have careful control over what gets written
```

cc @pfrazee

**Comment by pfrazee** [comment]
Yeah. I'd like to have a flow similar to git's staging (but very open to being streamlined).

I want to always know what I'm about to write to the log, and be able to control that update on a per-file basis.

**Comment by joehand** [comment]
I liked some of the ideas in [gitless](http://gitless.com/), specifically marking files tracked or untracked, and [the paper](http://people.csail.mit.edu/sperezde/onward13.pdf) is definitely worth a read in thinking about staging areas.

**Comment by pfrazee** [comment]
Yeah that looks like it'd work really well for this

**Comment by pfrazee** [comment]
My biggest complaint about gitless is that I'd feel a little unsure of what happens to tracked files when you branch. That wouldnt be a problem here.

**Comment by okdistribute** [comment]
I feel weary about having a data sharing tool not import your files by default. seems like a high barrier to entry.

**Comment by pfrazee** [comment]
Ok yall can do what you want here; I've got bkr now, so that flow works the
way I want it to.

**Comment by joehand** [comment]
I could an argument for why `create` could have `--no-import` as the default. That way, you can quickly create a dat, then do `dat sync` to start sharing while files are being imported.

But probably having it be consistent with sync is better. Closing for now and we can reevaluate with more user testing.

**Comment by okdistribute** [comment]
@joehand ah so then `create` would work more like `git init` or something?

**Comment by okdistribute** [comment]
@joehand but would that cause issues if `sync` was watching files?

**Comment by joehand** [comment]
> @joehand ah so then create would work more like git init or something?

Yep! 

> @joehand but would that cause issues if sync was watching files?

Sync imports and new/updated files (`--import` option is true by default). In this case it'd be all of the files.

You can run `dat-next create --no-import`. Then `dat-next sync --import` to see how it'd work.

**Comment by okdistribute** [comment]
@joehand wasn't there a bug with adding files while doing watching/importing?

**Comment by joehand** [comment]
> @joehand wasn't there a bug with adding files while doing watching/importing?

Yes but the bug is with live watching, not importing. Right now with sync it doesn't watch anything - it just imports newer files (which is relatively bug free). The bugs start if we change `live: true` [here](https://github.com/joehand/dat-next/blob/master/lib/share.js#L64).

**Comment by okdistribute** [comment]
ah yeah, thats what i meant. So either way, without or with watching files we still should have the import step be separate than the watching step. could be in the `sync` command, though.
