### ISSUE TITLE
'init' instead of 'create' ?

### ISSUE THREAD

**Issue by pfrazee** [joehand/dat-next#2]
I personally like init more, but that's a small thing

**Comment by joehand** [comment]
Ya I went back and forth on this. I think create may be a bit more friendly but init is more common for seasoned developers. We could alias init to create.

**Comment by pfrazee** [comment]
Here's my reasoning: New people are going to have to look up the command,
no matter what, so what's the difference between init or create? Meanwhile
seasoned devs will guess init from experience.

**Comment by okdistribute** [comment]
init is also fewer letters

**Comment by joehand** [comment]
Ya I'm going to alias them. Then we can decide later =).
