### ISSUE TITLE
Up-to-date archive doesn't finish pull or sync

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#24]
[hypercore bug](https://github.com/mafintosh/hypercore/issues/34) causes bad behavior when running sync or pull on an up-to-date archive.

**Comment by okdistribute** [comment]
It looks like this function is only called after an append or on finalize: https://github.com/mafintosh/hypercore/blob/dbc68f37d6381f82723a5bffcb579123e32e7a48/lib/feed.js#L573
