### ISSUE TITLE
push to hyperarchiver server

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#27]
`dat-next push` in a created dat folder should push to the authenticated server.

Workflow:

1. Register/Login: `dat-next login --server datfolder` (datfolder should be default?) **DONE**
2. Create a dat in a folder w/ data: `dat-next create` **DONE**
3. Push Dat: `dat-next push`
  3a. Server adds to hypercore-archiver over http **DONE** ([archiver-api](https://github.com/joehand/archiver-api#apiaddreq-res-ctx-cb))
  3b. Dat Client joins swarm after http response
  3c. Server can show progress **DONE!**
  3d. Client can know when finished (?)
4. Client closes swarm and exits.

Sidenote: hypercore-archiver doesn't track who added archives belong to. That is probably also necessary before we ship this.

**Comment by okdistribute** [comment]
yeah lets make datfolder the default for now

for progress, we might be able to have an http endpoint that the client can ping every 5 seconds or so that returns the stats

**Comment by joehand** [comment]
Added progress request function to the [archiver-api](https://github.com/joehand/archiver-api#apiarchiveprogressreq-res-ctx-cb).
