### ISSUE TITLE
Make auth server/config setting easier for development

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#29]
It'd be sweet if you could test against the local config/auth server by setting `ENV=development` or passing a `--dev-auth` flag or something.

Right now you have to test with:

```
dat-next login  --email joe --password joe --server http://localhost:8080 --config ./test.txt
```

**Comment by okdistribute** [comment]
whats `--config`? maybe there's a `~/.datrc` you can create that dat will default to.

**Comment by joehand** [comment]
> whats --config? maybe there's a ~/.datrc you can create that dat will default to.

That sets the config file for township. Yes, it'll default to `~/.datrc` but I just wanted to use another for testing so we don't overwrite the actual config file.
