### ISSUE TITLE
[cmd] FORK - copy another archive and reset metadata

### ISSUE THREAD

**Issue by pfrazee** [joehand/dat-next#3]
It'd be neat to have a fork command that's similar to what's in beaker.

Download the current files, then create a new dat and populate it with them.

**Comment by joehand** [comment]
This would be nice. My only hesitation is that it may imply that we have a merge/PR workflow, similar to git. 

Since it is pretty easy to do by hand, we may want to wait on this one:

```
dat-verb clone <link> my_data
cd my_data
rm -rf .dat
dat-verb create
```

**Comment by pfrazee** [comment]
Totally cool with not doing this now, but I dont think it suggests merging.
Branching would, but forking is about making a fresh copy.

**Comment by okdistribute** [comment]
+1 on forking now. Say "merge not implemented pr's welcome!"

**Comment by joehand** [comment]
This issue was moved to datproject/dat#653
