### ISSUE TITLE
Populate .gitignore on create

### ISSUE THREAD

**Issue by pfrazee** [joehand/dat-next#4]
Since it can be disastrous to commit the .dat folder, I suggest we create a .gitignore file if it DNE, and append .dat to it.

**Comment by joehand** [comment]
Yes. Ideally we'd do store them elsewhere, #41. 

If that isn't landed by the time we release this as the main CLI, we'll implement this.

**Comment by joehand** [comment]
This issue was moved to datproject/dat#652
