### ISSUE TITLE
shortcut for dat /dir

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#54]
Backwards compatible with sync command. 

`dat-next sync .` === `dat-next .`

**Comment by okdistribute** [comment]
In the old version it would create and sync for you if there was no previous dat when doing `dat dir` -- do we want to remove that capability?

**Comment by joehand** [comment]
> In the old version it would create and sync for you if there was no previous dat when doing dat dir -- do we want to remove that capability?

Yes, I'd like to remove that. I think it hides a bit too much what is going on. It also made maintenance on the old CLI harder because of all the guesswork involved in what the user was trying to do.

I think the latter will be less of an issue with this new code base. But I'd still be wary of combining them, especially if we want to add any init questions, like `npm init`, to populate `dat.json`.

The downside is that for large dats it can take a lot longer to start sharing files. The shortcut for that would be to run `dat create --no-import && dat sync`. But definitely wouldn't be obvious to do that.

**Comment by joehand** [comment]
@karissa shipped the basic shortcut in PR #58 but let me know if you think we should also add the create step.
