### ISSUE TITLE
[cmd] STATUS - show status of a local dat

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#57]
`dat status`

## v1

Show information about the dat in a folder (without connecting to network)

- [ ] total size
- [ ] how much is synced (based on last connection()
- [ ] Last sync date

## v2

Show information with network connection

- [ ] Whether up to date
- [ ] Health?

**Comment by joehand** [comment]
Started this in the [status-cmd](https://github.com/joehand/dat-next/tree/status-cmd) branch. Right now it prints metadata blocks and content blocks.

**Comment by okdistribute** [comment]
do we need this for `2.2.0`?

**Comment by joehand** [comment]
This issue was moved to datproject/dat#649
