### ISSUE TITLE
File count when owner include duplicates

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#71]
Reproduce:

1. `dat create` in folder with 10 files (for example)
2. `echo 'test' > 'new-file.txt'`
3. `dat sync` shows 11 files (correct)
4. `echo 'bigger test' > 'new-file.txt'`
5. `dat sync` currently show 12 files (this is incorrect)

Then if you do `dat clone <link>` it will show 11 files. I thought hyperdrive-stats should handle this. Are we using the wrong stats? Is this a bug in hyperdrive stats?

**Comment by okdistribute** [comment]
there's only 11 files total, 

`dat sync` shouldn't show 12 files if you're just appending to the same file name

**Comment by joehand** [comment]
Yes, that is the issue 😄 , it shows 12 right now.

**Comment by joehand** [comment]
Ah was using the wrong stats! Using the imported number (total files imported incl. duplicates) not the hyperdrive stats number.
