### ISSUE TITLE
Transfer of dats sometimes has the connection reset every few seconds

### ISSUE THREAD

**Issue by beingalink** [joehand/dat-next#73]
Regarding the transfer of my test dat it seems like the connection gets reset every few seconds: <https://owncloud.beingalink.de/s/m7H9PJUhZy2aSck>

This is strange since it also sometimes works fine with full speed without the connection resets.

I was advised to cc @mafintosh

**Comment by beingalink** [comment]
I reinstalled dat-next on the vps for no reason and recreated the dat and now the transfer is without the resets and much faster: <https://owncloud.beingalink.de/s/3gQCo2nL6MfX0QV>

I just can't explain why it's so inconsistent.

**Comment by joehand** [comment]
`2.1.0` improved download speed printing and is a bit less aggressive in removing the speed (was incorrectly setting speed to zero before when it shouldn't have). 

I think those fixed the issue but please reopen if you see more. Thanks!
