### ISSUE TITLE
Outline issues/features to release as main CLI

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#74]
Per call: it may be easier/better to release as the main CLI for user testing.

What features and bugs do we need to address before releasing as main CLI? (update milestones to reflect)

**Comment by okdistribute** [comment]
Which milestone are we using for this? You have two milestones (Dat CLi and Dat 2.2.0)

**Comment by joehand** [comment]
Updated the [milestones](https://github.com/joehand/dat-next/milestones) 🏁 . Current thinking for the next milestones:

* [dat-next 2.2.0](https://github.com/joehand/dat-next/milestone/4) - release early version of live file watching asap so we can test a bit
* [datproject/dat release](https://github.com/joehand/dat-next/milestone/5) - Fix any live watching bugs and perhaps add a few basic but nice features.
* move & release `dat` on npm! 🚌

**Comment by joehand** [comment]
See milestones. 🎆
