### ISSUE TITLE
docs issues before transfer

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#79]
Right now the `datproject/dat` readme is the landing page of the docs. We need to either update this one before we move it back to other repo ~or use another page as landing~.

**Comment by okdistribute** [comment]
What page would you rather have as the landing? Ideas for what the content structure might be?

I think you can set this in content.json

**Comment by okdistribute** [comment]
But I like the idea of having a nice readme that can also suffice as the first page of the docs since people can come to dat either from the github or the other site :)

**Comment by joehand** [comment]
> But I like the idea of having a nice readme that can also suffice as the first page of the docs since people can come to dat either from the github or the other site :)

Ya thats what we had talked about with it before. 

Just looked at how it looks with the sub-header links and that actually works really nice with the readme. Yay! So let's do readme + landing as it is right now.

**Comment by joehand** [comment]
TODO: 

- [x] update README here as discussed above (in progress)
- [x] move all the code to datproject/dat
- [x] update docs.datproject.org
  - [x] run script to update readme
  - [x] check for other outdated dat cli references
- [x] release v12 on npm as `dat`
- [x] move issues from this repo -> datproject/dat. cleanup titles/consolidate if possible. let issue contributors know.
- [x] cleanup old v11 issues. close if fixed in v12, etc.
- [x] add deprecation note to readme
- [x] deprecate on npm

(this TODO list will be moved to datproject/dat sometime)
