### ISSUE TITLE
Evaluate existing CLI options and implement

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#8]
Dat currently has the following options:

```

Sharing
  --watchFiles          watch files for changes (beta: still in development)
  --snapshot            create a snapshot of directory

Downloading
  --exit                exit process after download finishes

  --version, -v         get installed dat version
  --temp                use in-memory database instead of .dat folder
  --doctor              run dat doctor
  --quiet, -q           output only dat-link, no progress information
  --debug               show debugging output
  --ignore-hidden       ignore hidden files (true by default)
  --port, -p            set a specific inbound tcp port
```

We need to implement (add things here if we want to keep them):

- [ ] `--watch-files` discussion in #7
- [x] `--snapshot`
- [x] `--version`
- [x] `--temp`
- [x] `--doctor`
- [ ] logging options
  - [x] `--quiet`
  - [ ] `--debug`: add `debug` package and better debugging info too!
- [x] network options
  - [x] `--port`
  - [x] `--utp`

**Comment by okdistribute** [comment]
how do you imagine `--temp` would work? just on `sync`?

**Comment by joehand** [comment]
> how do you imagine --temp would work? just on sync?

Oh ya, did not think that through. No idea! I don't really like having it as a sync option, that doesn't quite make sense.

Could it be it's own command that would create + share? 

This was an issue I was having with snapshot as well. For snapshot/temp it may be nice to create and sync without doing two commands. For both you'll only want to import once.

**Comment by okdistribute** [comment]
PR open for --temp on clone: https://github.com/joehand/dat-next/pull/19

**Comment by joehand** [comment]
Closing. Remaining issues:

* [deubbing](https://github.com/joehand/dat-next/issues/21)
* [live watch](https://github.com/joehand/dat-next/issues/7)

We'll evaluate any missing options after user testing.
