### ISSUE TITLE
Do not delete users data!

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#80]
There is a line in `downoad.js` that deletes the folder if there was an error (for bad clones). We should make sure we created the dir before deleting it. Had a weird bug where I was syncing and it ended up in download and deleted the folder. Very not good.

[link to the line comment.](https://github.com/joehand/dat-next/blob/master/lib/download.js#L93)

**Comment by okdistribute** [comment]
yeah maybe we should just remove that line and if the clone errors people can rm -rf foldername. 

maybe also we could include a `dat clean` command because some people don't know how to `rm -rf`

**Comment by joehand** [comment]
What do you think about https://github.com/joehand/dat-next/pull/87? It should only get there [if the key is a hypercore feed](https://github.com/joehand/dat-next/blob/master/lib/download.js#L63). 

It had happened to me because I was messing around with hypercore and changing keys to make non-archive things - so pretty edge case =).

+1 for `dat clean` but probably wait for release on that.
